value1 = float(input("Inserta un valor: "))
value2 = float(input("Inserta otro valor: "))
print("Suma: ",value1," + ",value2, " = ",value1+value2)
print("Resta: ",value1," - ",value2, " = ",value1-value2)
print("Multiplicacion: ",value1," * ",value2, " = ",value1*value2)
print("Division: ",value1," / ",value2, " = ",value1/value2)
print("\n¡Eso es todo, amigos!")
