print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")

print()
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")

print()
print("        **")
print("      **  **")
print("    **      **")
print("  **          **")
print("******      ******")
print("    **      **")
print("    **      **")
print("    **********")

print("    *    "*2)
print("   * *   "*2)
print("  *   *  "*2)
print(" *     * "*2)
print("***   ***"*2)
print("  *   *  "*2)
print("  *   *  "*2)
print("  *****  "*2)

print()
print()
#print("    *) Indica error en linea 34 de main.py,EOL while scanning string literal
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")

print()
print()
#print("    *" Indica error en linea 47 de main.py, invalid syntax
#es decir, el programa lee la linea correctamente y se percata del error en el siguiente print
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")

print()
print()
#Print("    *") Indica error en linea 57 de main.py, name 'Print' is not defined
#es decir, el programa se percata del error al instante
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")

print()
print('    *')
print('   * *')
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
#Acepta los apostrofes en lugar de comillas
